name = "livescores"
type = "webpack"

account_id = "f76e74d189405c0cc9483a98acb6bdd0"
workers_dev = true
route = ""
zone_id = "6827e2098c7341871321cc4745064ab5"
node_compat = true
compatibility_date = "2023-01-14"